// QUERY KEYS
export const QUERY_KEYS = {
  pillarList: "pillar_list",
  courseSlider: "course_slider",
  trainerList: "trainer_list",
  bannerSlider: "banner_slider",
  questionList: "question_list",
  companyList: "company_list",
  oneCompany: "one_company",
  assessment: "assessment",
  totalAssessment: "total_assessment",
  clientwiseBannerSlider: "clientwise_banner_slider",
  clientwiseCourseSlider: "clientwise_course_slider",
  fetchDataByClientwise: "fetch_data_by_clientwise",
  clientwisePillarList: "clientwise_pillar_list",
  getQuestionAnswer: "get_question_answer",
  maturityLevel: "maturity_level",
  fetchbyclientMaturity: "fetch_by_client_maturity",
  maturitypillar: "maturity_pillar",
  filterMaturityMeasures: "filter_maturity_measures",
  measuresItems: "measures_items",
  updatePillar: "update_pillar",
  checkedMeasures: "checked_measures",
  themeChanges: "theme_Changes",
  fetchbycourse: "course",
  authenums: "authenums",
  enumUpadateList: "enum_upadate_list",
  fetchbyallcourse: "allcourse",
  fetchbycourseallocate: "allocatedcourse",
  fetchbyrecommendedcourse: "recommendedcourses",
  fetchbypillarcource: "fetchbypillarcource",
  fetchbypillar: "fetchbypillar",
  fetchEnrollmentRequestBytrainer: "fetch_enrollment_request_by_trainer",
  fetchAllCourse: "fetchAllCourse",
  companyDetailsId: "companyDetailsById",
  fetchbycourseallocateById: "fetchbycourseallocateById",
  chatUserList: "chatUserList",
  chatList: "chatList",
  clientList: "clientList",
  emailTemplate: "emailTemplate",
  companyOrTrainerCompany: "companyOrTrainerCompany",
};

export const urlRegex =
  /((([A-Za-z]{3,9}:(?:\/\/)?)(?:[-;:&=\+\$,\w]+@)?[A-Za-z0-9.-]+|(?:www.|[-;:&=\+\$,\w]+@)[A-Za-z0-9.-]+)((?:\/[\+~%\/.\w-_]*)?\??(?:[-\+=&;%@.\w_]*)#?(?:[\w]*))?)/;
