# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on:  self-hosted

    strategy:
      matrix:
        node-version: [ 18.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Clear npm cache
        run: npm cache clean --force

      - name: Clear GitHub Actions cache
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set environment variables in .env file
        run: |
          echo VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }} >> .env
          echo VITE_SOCKET_URL=${{ secrets.VITE_SOCKET_URL }} >> .env
          echo VITE_AWS_REGION=${{ secrets.VITE_AWS_REGION }} >> .env   
          echo VITE_AWS_ACCESS_KEY_ID=${{ secrets.VITE_AWS_ACCESS_KEY_ID }} >> .env   
          echo VITE_AWS_SECRET_ACCESS_KEY=${{ secrets.VITE_AWS_SECRET_ACCESS_KEY }} >> .env   
          echo VITE_BUCKETNAME=${{ secrets.VITE_BUCKETNAME }} >> .env   
          echo VITE_CLOUD_MESSAGE_VAPIDKEY=${{ secrets.VITE_CLOUD_MESSAGE_VAPIDKEY }} >> .env   
      - run: npm install -force
      - run: npm run build 
      - run: pm2 restart frontend
  
